### ISSUE TITLE
Translation for 'display' not found 

### ISSUE THREAD

**Issue by rantonse** [youngcut/kirby-form-block-suite#16]
I am getting “Translation for 'display' not found" instead of {{name}} ({{email}}) in the Inbox.

To reproduce the error, I installed

- https://github.com/getkirby/starterkit/releases/tag/3.9.2
- https://github.com/youngcut/kirby-form-block-suite/releases/tag/v3.4.5

then added a form and submitted it.

**Comment by ellewilliams** [comment]
I am having the same issue!

**Comment by alexsmoli** [comment]
Same unfortunately...any solution?

**Comment by youngcut** [comment]
Thanks for your patience. It is fixed in version 3.4.6.
The requests name are unfortunately still displayed as before. Sorry for this inconvenience.
Please check the display field in Kirby, if the error still appears.

<img width="775" alt="Bildschirmfoto 2023-03-25 um 11 21 48" src="https://user-images.githubusercontent.com/4754476/227714507-db82d128-6f5e-417e-b207-815d601d5632.png">

**Comment by ellewilliams** [comment]
I am still having this issue even after updating, sorry.

**Comment by youngcut** [comment]
Do you see the field on the image from my last post?

**Comment by ellewilliams** [comment]
Yes, I have realised today after getting 2 new messages that this is working for new ones but the old ones still show 'Translation for 'display' not found'. Not a problem to worry about, thanks.
