### ISSUE TITLE
Not working - Send form without reloading the page

### ISSUE THREAD

**Issue by mactedder80** [youngcut/kirby-form-block-suite#2]
I have upgraded from the old Form Block App, but my forms are still reloading on submit. Did I miss anything when updating from the old plugin?

I replace the plugin folder.
I am still using my previous form.php file is this ok.

Also all my enquiries now just say 'en' in the drawers inbox section. Previously they used to show the users name and email.

**Comment by youngcut** [comment]
Thank for you feedback.

Did you modify the form.php file in you project folder perviously? Or different asked: Is this file exists: `site/snippets/blocks/form.php`?
Than you should backup that file, copy the same from `site/plugins/kirby-form-block-suite/snippets/blocks/form.php` and modify it as you like. Some new code where added here to make the submit without reload working.

Because the bug with the naming: Did the enquiries with name 'en' made with the new version or (also/just) the one who created with the old version?
The way the plugin named the enquiries in now set under the formfields. The name will be set at the time, the visitor send the request. Do you know what i mean?

**Comment by mactedder80** [comment]
All sorted now. I have used the new form.php file and it validates without reloading the page.

**Comment by youngcut** [comment]
I found the Bug why the Plugin returns "en" if the Placeholder not found and fix it in version 3.2-BETA.
But in your case it will show now "", cause your placeholder is missing. Waiting for your reply of my last question.

**Comment by mactedder80** [comment]
Yes placeholders were missing. The help text needs finishing. It currently says:

"Needed to display the emails in the panel. You can use the unique identifier of the fields as placeholder (e.g. )"

It should say something like:

"Needed to display the emails in the panel. You can use the unique identifier of the fields as placeholder (e.g. ) {{given-name}} {{family-name}} - {{email}} "

**Comment by youngcut** [comment]
Thank for you input. It will fixed in the next release...
